# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module SwaggerPetstore
  class StatusEnum
    # TODO: Write general description for PLACED
    # TODO: Write general description for APPROVED
    # TODO: Write general description for DELIVERED
    STATUS_ENUM = [PLACED = 'placed', APPROVED = 'approved', DELIVERED = 'delivered']
  end
end