# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module SwaggerPetstore
  class Status6Enum
    # TODO: Write general description for AVAILABLE
    # TODO: Write general description for PENDING
    # TODO: Write general description for SOLD
    STATUS_6_ENUM = [AVAILABLE = 'available', PENDING = 'pending', SOLD = 'sold']
  end
end