# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module SwaggerPetstore
  class Configuration
    # The base Uri for API calls
    @base_uri = 'http://petstore.swagger.io/v2'

    # The OAuth 2.0 access token to be set before API calls
    @o_auth_access_token = 'TODO: Replace'

    # The attribute accessors for public properties
    class << self
      attr_accessor :array_serialization
      attr_accessor :base_uri
      attr_accessor :o_auth_access_token
    end
  end
end
