# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
require 'date'
require 'json'
require 'faraday'
require 'certifi'
require 'logging'

require_relative 'swagger_petstore/api_helper.rb'
require_relative 'swagger_petstore/swagger_petstore_client.rb'

# Http
require_relative 'swagger_petstore/http/http_call_back.rb'
require_relative 'swagger_petstore/http/http_client.rb'
require_relative 'swagger_petstore/http/http_method_enum.rb'
require_relative 'swagger_petstore/http/http_request.rb'
require_relative 'swagger_petstore/http/http_response.rb'
require_relative 'swagger_petstore/http/http_context.rb'
require_relative 'swagger_petstore/http/faraday_client.rb'
require_relative 'swagger_petstore/http/auth/o_auth_2.rb'

# Models
require_relative 'swagger_petstore/models/base_model.rb'
require_relative 'swagger_petstore/models/tag.rb'
require_relative 'swagger_petstore/models/category.rb'
require_relative 'swagger_petstore/models/api_response.rb'
require_relative 'swagger_petstore/models/pet.rb'
require_relative 'swagger_petstore/models/order.rb'
require_relative 'swagger_petstore/models/user.rb'
require_relative 'swagger_petstore/models/status_6_enum.rb'
require_relative 'swagger_petstore/models/status_enum.rb'

# Exceptions
require_relative 'swagger_petstore/exceptions/api_exception.rb'

require_relative 'swagger_petstore/configuration.rb'

# Controllers
require_relative 'swagger_petstore/controllers/base_controller.rb'
require_relative 'swagger_petstore/controllers/user_controller.rb'
require_relative 'swagger_petstore/controllers/store_controller.rb'
require_relative 'swagger_petstore/controllers/pet_controller.rb'
